apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  # serves a similar purpose as localhost or 127.0.0.1 in a local development environment. It allows pods within the Kubernetes cluster to access services running on the Minikube host machine.
  MYSQL_HOST: host.minikube.internal
  MYSQL_USER: auth_user
  MYSQL_DB: auth
  MYSQL_PORT: "3306"